[[redirects]]
  from = "https://newsapi.org/v2/top-headlines?country=us&apiKey=e37f8ac9358c4dbd900f1a0ba2694e50"
  to = "https://news-nation.netlify.app/news"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {Access-Control-Allow-Origin: *}
  